/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vuhuy
 */
public class giaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giaoDien.class.getName());
    ArrayList<matHang> danhSachMatHang;
    /**
     * Creates new form giaoDien
     */
    public giaoDien() {
        initComponents();
        danhSachMatHang=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        buttonTienTe = new javax.swing.JRadioButton();
        thongTinThem = new javax.swing.JLabel();
        txtThongTinThem = new javax.swing.JTextField();
        buttonTrangSuc = new javax.swing.JRadioButton();
        buttonMuaBan = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma hang", "Ten hang", "Duoc phep mua hang", "Gia theo can/Ty gia"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Nhap file");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Hien thi");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Tim kiem");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setText("Ma hang");

        txtMaHang.addActionListener(this::txtMaHangActionPerformed);

        jLabel2.setText("Ten hang");

        buttonGroup2.add(buttonTienTe);
        buttonTienTe.setText("Tien te");
        buttonTienTe.addActionListener(this::buttonTienTeActionPerformed);

        thongTinThem.setText("Thong tin them");

        txtThongTinThem.addActionListener(this::txtThongTinThemActionPerformed);

        buttonGroup2.add(buttonTrangSuc);
        buttonTrangSuc.setText("Trang suc");
        buttonTrangSuc.addActionListener(this::buttonTrangSucActionPerformed);

        buttonMuaBan.setText("Duoc phep mua ban");
        buttonMuaBan.addActionListener(this::buttonMuaBanActionPerformed);

        jButton4.setText("Them tien te");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Them trang suc");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Xuat file");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonMuaBan)
                        .addGap(64, 64, 64)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thongTinThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtThongTinThem))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonTienTe)
                            .addComponent(buttonTrangSuc))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(540, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(517, 517, 517))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1)
                        .addGap(12, 12, 12)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTienTe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTrangSuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thongTinThem)
                    .addComponent(txtThongTinThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMuaBan)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            FileReader fr=new FileReader("mathang.txt");
            BufferedReader br=new BufferedReader(fr);
            String line="";
            while((line=br.readLine())!=null){
                String[] data=line.split(",");
                String loai=data[0];
                int ma=Integer.parseInt(data[1]);
                String ten=data[2];
                boolean muaban=Boolean.parseBoolean(data[3]);
                double phu=Double.parseDouble(data[4]);
                if(loai.equals("TienTe")){
                    tienTe tt=new tienTe(ma, ten, muaban, phu);
                    danhSachMatHang.add(tt);
                }else{
                    trangSuc ts=new trangSuc(ma, ten, muaban, phu);
                    danhSachMatHang.add(ts);
                }
            }
            br.close();
            fr.close(); 
            JOptionPane.showMessageDialog(this, "Luu file thang cong");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi đọc file!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hienThiLenBang(danhSachMatHang);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String input=txtTimKiem.getText().trim();
            if(input.isEmpty()){
                JOptionPane.showMessageDialog(this, "Dien vao di");
                return;
            }
            int maCanTim=Integer.parseInt(input);
            ArrayList<matHang> ketqua=new ArrayList<>();
            boolean timthay=false;
            for(matHang mh : danhSachMatHang){
                if(mh.getMaHang()==maCanTim){
                    ketqua.add(mh);
                    timthay=true;
                }
            }
            if(timthay){
                hienThiLenBang(ketqua);
            }else{
                int chon=javax.swing.JOptionPane.showConfirmDialog(this, "Không tìm thấy mặt hàng mã " + maCanTim + ". Bạn có muốn thêm mới không?", "Thông báo", javax.swing.JOptionPane.YES_NO_OPTION);               
                if (chon==javax.swing.JOptionPane.YES_OPTION) {
                    txtMaHang.setText(txtTimKiem.getText());
                    txtTimKiem.setText(null);
                }        
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "So nguyen only");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonTienTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTienTeActionPerformed
        // TODO add your handling code here:
            thongTinThem.setText("Ty gia chuyen doi");
    }//GEN-LAST:event_buttonTienTeActionPerformed

    private void buttonTrangSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrangSucActionPerformed
        // TODO add your handling code here:
            thongTinThem.setText("Gia theo can");
    }//GEN-LAST:event_buttonTrangSucActionPerformed

    private void buttonMuaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMuaBanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonMuaBanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tienTe tt=new tienTe();
        tt.setMaHang(Integer.parseInt(txtMaHang.getText()));
        tt.setTenHang(txtTenHang.getText());
        tt.setTyGiaChuyenDoi(Double.parseDouble(txtThongTinThem.getText()));
        tt.setDuocPhepMuaBan(buttonMuaBan.isSelected());
        danhSachMatHang.add(tt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtMaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHangActionPerformed

    private void txtThongTinThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThongTinThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThongTinThemActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        trangSuc ts=new trangSuc();
        ts.setMaHang(Integer.parseInt(txtMaHang.getText()));
        ts.setTenHang(txtTenHang.getText());
        ts.setGiaTheoCan(Double.parseDouble(txtThongTinThem.getText()));
        ts.setDuocPhepMuaBan(buttonMuaBan.isSelected());
        danhSachMatHang.add(ts);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
        java.io.FileWriter fw = new java.io.FileWriter("mathang.txt");
        java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
        for (matHang mh : danhSachMatHang) {
            String line = "";
            String loai = "";
            double thongTinRieng = 0;
            if (mh instanceof tienTe) {
                loai = "TienTe";
                thongTinRieng = ((tienTe) mh).getTyGiaChuyenDoi();
            } else if (mh instanceof trangSuc) {
                loai = "TrangSuc"; 
                thongTinRieng = ((trangSuc) mh).getGiaTheoCan();
            }
            line = loai + "," + mh.getMaHang() + "," + mh.getTenHang() + "," + mh.isDuocPhepMuaBan() + "," + thongTinRieng;
                bw.write(line);
                bw.newLine(); // Xuống dòng
            }
            bw.close();
            fw.close();
        
            javax.swing.JOptionPane.showMessageDialog(this, "Xuất file thành công!");
        
        } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi xuất file!");
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    private void hienThiLenBang(ArrayList<matHang> list){
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        model.setRowCount(0);
        double thongTinRieng=0;
        for(matHang mh : list){
            if(mh instanceof tienTe){
                double cd = ((tienTe) mh).getTyGiaChuyenDoi();
                thongTinRieng=cd;
            }else if (mh instanceof trangSuc){
                double tc=((trangSuc) mh).getGiaTheoCan();
                thongTinRieng=tc;
            }
            model.addRow(new Object[]{
            mh.getMaHang(),
            mh.getTenHang(),
            mh.isDuocPhepMuaBan(),
            thongTinRieng
            });
        }    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giaoDien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton buttonMuaBan;
    private javax.swing.JRadioButton buttonTienTe;
    private javax.swing.JRadioButton buttonTrangSuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JLabel thongTinThem;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtThongTinThem;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
