/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vuhuy
 */
public class giaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giaoDien.class.getName());
    ArrayList<thiSinh> danhSachThiSinh;
    /**
     * Creates new form giaoDien
     */
    public giaoDien() {
        initComponents();
        danhSachThiSinh = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Diem1 = new javax.swing.JLabel();
        Diem2 = new javax.swing.JLabel();
        Diem3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSoBaoDanh = new javax.swing.JTextField();
        txtTruongHoc = new javax.swing.JTextField();
        txtDiemCong = new javax.swing.JTextField();
        txtDiem1 = new javax.swing.JTextField();
        txtDiem2 = new javax.swing.JTextField();
        txtDiem3 = new javax.swing.JTextField();
        button1 = new javax.swing.JRadioButton();
        button2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ho ten");

        jLabel2.setText("So bao danh");

        jLabel3.setText("Truong hoc");

        jLabel4.setText("Diem cong");

        Diem1.setText("Diem 1");

        Diem2.setText("Diem 2");

        Diem3.setText("Diem 3");

        buttonGroup1.add(button1);
        button1.setText("Khoi A");
        button1.addActionListener(this::button1ActionPerformed);

        buttonGroup1.add(button2);
        button2.setText("Khoi D");
        button2.addActionListener(this::button2ActionPerformed);

        jButton1.setText("Them khoi A");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Them khoi D");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho ten", "So bao danh", "Truong hoc", "Diem cong", "Tinh diem"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton3.setText("> 8");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("< 3");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Hien bang");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Xuat file");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTruongHoc)
                                    .addComponent(txtSoBaoDanh)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(Diem1)
                                    .addComponent(Diem2)
                                    .addComponent(Diem3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDiem3)
                                            .addComponent(txtDiem2)
                                            .addComponent(txtDiem1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDiemCong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button2))
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1)
                    .addComponent(button2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoBaoDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTruongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diem1)
                    .addComponent(txtDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diem2)
                    .addComponent(txtDiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diem3)
                    .addComponent(txtDiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if(button1.isSelected()){
            Diem1.setText("Diem toan");
            Diem2.setText("Diem ly");
            Diem3.setText("Diem hoa");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(button2.isSelected()){
            Diem1.setText("Diem toan");
            Diem2.setText("Diem van");
            Diem3.setText("Diem anh");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        khoiA ka=new khoiA();
        ka.setHoTen(txtHoTen.getText());
        ka.setSoBaoDanh(Integer.parseInt(txtSoBaoDanh.getText()));
        ka.setTruongHoc(txtTruongHoc.getText());
        ka.setDiemCong(Double.parseDouble(txtDiemCong.getText()));
        ka.setDiemToan(Double.parseDouble(txtDiem1.getText()));
        ka.setDiemLy(Double.parseDouble(txtDiem2.getText()));
        ka.setDiemHoa(Double.parseDouble(txtDiem3.getText()));
        if(button1.isSelected()){
            ka.tinhDiem();
            danhSachThiSinh.add(ka);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        khoiD kd=new khoiD();
        kd.setHoTen(txtHoTen.getText());
        kd.setSoBaoDanh(Integer.parseInt(txtSoBaoDanh.getText()));
        kd.setTruongHoc(txtTruongHoc.getText());
        kd.setDiemCong(Double.parseDouble(txtDiemCong.getText()));
        kd.setDiemToan(Double.parseDouble(txtDiem1.getText()));
        kd.setDiemVan(Double.parseDouble(txtDiem2.getText()));
        kd.setDiemAnh(Double.parseDouble(txtDiem3.getText()));
        if(button2.isSelected()){
            kd.tinhDiem();
            danhSachThiSinh.add(kd);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        hienThiLenBang(danhSachThiSinh);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter fw = new FileWriter("thisinh.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            for (thiSinh ts : danhSachThiSinh) {
                String line = "";
                line = ts.getHoTen() + ", " + ts.getSoBaoDanh() + ", " + ts.getTruongHoc() + ", " + ts.getDiemCong() + ", " + ts.tinhDiem();
                bw.write(line);
                bw.newLine(); 
            }
            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(this, "Lưu file thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lưu file!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<thiSinh> listLoc = new ArrayList<>();
        for (thiSinh ts : danhSachThiSinh) {
            if (ts.tinhDiem() > 8) {
                listLoc.add(ts);
            }
        }
        hienThiLenBang(listLoc);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<thiSinh> listLoc = new ArrayList<>();
        for (thiSinh ts : danhSachThiSinh) {
            if (ts.tinhDiem() < 3) { 
                listLoc.add(ts);
            }
        }
        hienThiLenBang(listLoc);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void hienThiLenBang(ArrayList<thiSinh> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (thiSinh ts : list) {
            model.addRow(new Object[]{
                ts.getHoTen(),
                ts.getSoBaoDanh(),
                ts.getTruongHoc(),
                ts.getDiemCong(),
                String.format("%.2f", ts.tinhDiem()) 
            });
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giaoDien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Diem1;
    private javax.swing.JLabel Diem2;
    private javax.swing.JLabel Diem3;
    private javax.swing.JRadioButton button1;
    private javax.swing.JRadioButton button2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDiem1;
    private javax.swing.JTextField txtDiem2;
    private javax.swing.JTextField txtDiem3;
    private javax.swing.JTextField txtDiemCong;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoBaoDanh;
    private javax.swing.JTextField txtTruongHoc;
    // End of variables declaration//GEN-END:variables
}
