/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vuhuy
 */
public class giaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giaoDien.class.getName());
    ArrayList<hangHoa> danhSachHangHoa;
    /**
     * Creates new form giaoDien
     */
    public giaoDien() {
        initComponents();
            danhSachHangHoa=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ten hang", "Ma hang", "Gia nhap", "Gia ban", "Sim/Kich thuoc", "Loi nhuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Nhap file");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Save data");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Sap xep");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Tim kiem");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTimKiem)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jButton4))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(179, 179, 179))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fr = new FileReader("hanghoa.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = "";
            while ((line = br.readLine()) != null) {
                String[] data = line.split(", ");
                
                String loai = data[0];
                int ma = Integer.parseInt(data[1]);
                String ten = data[2];
                double giaNhap = Double.parseDouble(data[3]);
                double giaBan = Double.parseDouble(data[4]);
                
                if (loai.equalsIgnoreCase("DT")) {
                    double sim = Double.parseDouble(data[5]);
                    dienThoai dt = new dienThoai(ten, ma, giaNhap, giaBan, sim);
                    danhSachHangHoa.add(dt);
                    
                } else if (loai.equalsIgnoreCase("MTB")) {
                    double kichThuoc = Double.parseDouble(data[5]);
                    mayTinhBang mtb = new mayTinhBang(ten, ma, giaNhap, giaBan, kichThuoc);
                    danhSachHangHoa.add(mtb);
                }
            }
            
            br.close();
            fr.close();          
            JOptionPane.showMessageDialog(this, "Đọc file thành công!");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi đọc file!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hienThiLenBang(danhSachHangHoa);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (danhSachHangHoa.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Danh sách trống!");
            return;
        }

        // Gọi hàm Quick Sort duy nhất
        quickSort(0, danhSachHangHoa.size() - 1);

        // Hiển thị kết quả
        hienThiLenBang(danhSachHangHoa);
        javax.swing.JOptionPane.showMessageDialog(this, "Đã sắp xếp xong!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String input = txtTimKiem.getText().trim();
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
                return;
            }
            int maCanTim = Integer.parseInt(input);
            ArrayList<hangHoa> ketQua = new ArrayList<>();
            boolean timThay = false;
            for (hangHoa hh : danhSachHangHoa) {
                if (hh.getMaHang() == maCanTim) {
                    ketQua.add(hh);
                    timThay = true;
                }
            }
            
            if (timThay) {
                hienThiLenBang(ketQua); 
            } else {
                JOptionPane.showMessageDialog(this, "Khong tim thay ma " + maCanTim);
                hienThiLenBang(danhSachHangHoa); 
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ma hang phai la so nguyen");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void hienThiLenBang(ArrayList<hangHoa> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        for (hangHoa h : list) {
            String thongTinRieng = "";

            if (h instanceof dienThoai) {
                thongTinRieng = String.valueOf(((dienThoai) h).getGiaSimGhep());
            } else if (h instanceof mayTinhBang) {
                thongTinRieng = String.valueOf(((mayTinhBang) h).getKichThuocManHinh());
            }

            model.addRow(new Object[]{
                h.getTenHang(),
                h.getMaHang(),
                h.getGiaNhap(),
                h.getGiaBan(),
                thongTinRieng,
                String.format("%,.0f", h.loiNhuan())
            });
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giaoDien().setVisible(true));
    }

    private void quickSort(int left, int right) {
        // Điều kiện dừng đệ quy
        if (left >= right) return;

        // B1: Chọn Pivot (Lợi nhuậ n của phần tử giữa)
        double pivot = danhSachHangHoa.get((left + right) / 2).loiNhuan();
        int i = left;
        int j = right;

        while (i <= j) {
            // Tìm phần tử bên trái <= Pivot (để đổi ra sau vì ta đang xếp GIẢM DẦN)
            while (danhSachHangHoa.get(i).loiNhuan() > pivot) {
                i++;
            }

            // Tìm phần tử bên phải >= Pivot (để đổi lên trước)
            while (danhSachHangHoa.get(j).loiNhuan() < pivot) {
                j--;
            }

            // Nếu phát hiện nghịch lý (trái nhỏ, phải lớn) -> Thực hiện SWAP ngay tại đây
            if (i <= j) {
                // --- BẮT ĐẦU ĐOẠN CODE SWAP ---
                hangHoa temp = danhSachHangHoa.get(i);
                danhSachHangHoa.set(i, danhSachHangHoa.get(j));
                danhSachHangHoa.set(j, temp);
                // --- KẾT THÚC ĐOẠN CODE SWAP ---

                i++;
                j--;
            }
        }

        // B3: Gọi đệ quy cho 2 nửa danh sách còn lại
        if (left < j) {
            quickSort(left, j);
        }
        if (i < right) {
            quickSort(i, right);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}

