
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vuhuy
 */
public class giaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giaoDien.class.getName());
    ArrayList<veBay> danhSachVeBay;
    

    
    /**
     * Creates new form giaoDien
     */
    public giaoDien() {
        initComponents();
        danhSachVeBay  = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        thongTinRieng = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtGiaVe = new javax.swing.JTextField();
        txtThongTinRieng = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button3 = new javax.swing.JRadioButton();
        button1 = new javax.swing.JRadioButton();
        button2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma ve");

        jLabel2.setText("Ho ten");

        jLabel3.setText("Gia ve");

        thongTinRieng.setText("Thong tin rieng");

        jButton1.setText("Them ve tg");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Them ve pt");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        button3.setText("Dich vu phong cho");

        buttonGroup1.add(button1);
        button1.setText("Ve pho thong");
        button1.addActionListener(this::button1ActionPerformed);

        buttonGroup1.add(button2);
        button2.setText("Ve thuong gia");
        button2.addActionListener(this::button2ActionPerformed);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma ve", "Ho ten", "Gia ve", "He so/Khoi luong", "Gia ban"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton3.setText("Hien thi");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Xuat file");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thongTinRieng)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaVe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThongTinRieng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtMaVe))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(button3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1)
                                .addGap(18, 18, 18)
                                .addComponent(button2)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1)
                    .addComponent(button2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thongTinRieng)
                    .addComponent(txtThongTinRieng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(115, 115, 115))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if(button1.isSelected()){
            thongTinRieng.setText("Khoi hanh ly ky gui");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(button2.isSelected()){
            thongTinRieng.setText("He so sang trong");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //thêm phần tử
        boolean choice=button3.isSelected();
        thuongGia tg = new thuongGia();
        tg.setMaVe(Integer.parseInt(txtMaVe.getText()));
        tg.setHoTen(txtHoTen.getText());
        tg.setGiaVe(Double.parseDouble(txtGiaVe.getText()));
        tg.setHeSoSangTrong(Double.parseDouble(txtThongTinRieng.getText()));
        tg.setDichVuPhongCho(choice);        
        if (button2.isSelected()) {
            danhSachVeBay.add(tg);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hienThiLenBang(danhSachVeBay);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //xuất file  xuatFile
    try {
        java.io.FileWriter fw = new java.io.FileWriter("vemaybay.txt");
        java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
        for (veBay vb : danhSachVeBay) {
            String line = "";
            String loai = "";
            double thongTinRieng = 0;
            if (vb instanceof thuongGia) {
                loai = "thuongGia";
                thongTinRieng = ((thuongGia) vb).getHeSoSangTrong();
            } else if (vb instanceof phoThong) {
                loai = "phoThong"; 
                thongTinRieng = ((phoThong) vb).getKhoiLuongHanhLy();
            }
            line = loai + "," + vb.getMaVe() + "," + vb.getHoTen() + "," + vb.getGiaVe() + "," + thongTinRieng;
                bw.write(line);
                bw.newLine(); // Xuống dòng
            }
            bw.close();
            fw.close();
        
            JOptionPane.showMessageDialog(this, "Xuất file thành công!");
        
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi xuất file!" + e);
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        phoThong pt = new phoThong();
        pt.setMaVe(Integer.parseInt(txtMaVe.getText()));
        pt.setHoTen(txtHoTen.getText());
        pt.setGiaVe(Double.parseDouble(txtGiaVe.getText()));
        pt.setKhoiLuongHanhLy(Double.parseDouble(txtThongTinRieng.getText()));    
        if (button1.isSelected()) {
            danhSachVeBay.add(pt);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giaoDien().setVisible(true));
    }
    
private void hienThiLenBang(ArrayList<veBay> list) {
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0);
    
    for (veBay vb : list) {
        String thongTinRieng = "";
        
        if (vb instanceof thuongGia) {
            thongTinRieng = String.valueOf(((thuongGia) vb).getHeSoSangTrong());
        } else if (vb instanceof phoThong) {
            thongTinRieng = String.valueOf(((phoThong) vb).getKhoiLuongHanhLy());
        }
        
        model.addRow(new Object[]{
            vb.getMaVe(),
            vb.getHoTen(),
            vb.getGiaVe(),
            thongTinRieng,
            String.format("%,.0f", vb.giaBan())
        });
    }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button1;
    private javax.swing.JRadioButton button2;
    private javax.swing.JRadioButton button3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JLabel thongTinRieng;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaVe;
    private javax.swing.JTextField txtThongTinRieng;
    // End of variables declaration//GEN-END:variables
}




