/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vuhuy
 */
public class giaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giaoDien.class.getName());
    private ArrayList<matHang> danhSachMatHang;
    /**
     * Creates new form giaoDien
     */
    public giaoDien() {
        initComponents();
        danhSachMatHang=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ten mat hang", "Ma hang", "So luong", "Gia von", "Gia tien menu", "Thuoc tinh con"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Save data");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Nhap file");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Sap xep");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Tim kiem");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hienThiLenBang(danhSachMatHang);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Hàm này để các nút khác gọi dùng chung, đỡ phải viết lại code hiển thị nhiều lần
    private void hienThiLenBang(ArrayList<matHang> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (matHang mh : list) {
            String thongTinRieng = "";
            
            // Kiểm tra xem là Món ăn hay Đồ uống để lấy thông tin riêng
            if(mh instanceof monAn){
                boolean td = ((monAn) mh).isCanTrinhDien();
                thongTinRieng = td ? "Có trình diễn" : "Không";
            }else if (mh instanceof doUong){
                boolean nong=((doUong) mh).isCoNongKhong();
                thongTinRieng=nong ? "Đồ nóng" : "Đồ lạnh";
            }

            model.addRow(new Object[]{
                mh.getTenMatHang(),
                mh.getMaHang(),
                mh.getSoLuong(),
                String.format("%,.0f", mh.getGiaVon()),
                String.format("%,.0f", mh.tinhGia()), // Cột Giá Menu (Quan trọng)
                thongTinRieng, // Cột riêng
            });
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fr = new FileReader("mathang.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = "";

            while ((line = br.readLine()) != null) {
                // Mẫu file: MA, 101, Bo Bit Tet, 10, 500000, true
                String[] data = line.split(", ");
                
                String loai = data[0];
                int ma = Integer.parseInt(data[1]);
                String ten = data[2];
                int soLuong = Integer.parseInt(data[3]);
                double giaVon = Double.parseDouble(data[4]);
                boolean thuocTinh = Boolean.parseBoolean(data[5]);
                if (loai.equals("MA")) {
                    monAn maObj = new monAn(ten, ma, soLuong, giaVon, thuocTinh);
                    danhSachMatHang.add(maObj);
                } else if (loai.equals("DU")) {
                    doUong duObj = new doUong(ten, ma, soLuong, giaVon, thuocTinh);
                    danhSachMatHang.add(duObj);
                }
            }
            br.close();
            fr.close();          
            JOptionPane.showMessageDialog(this, "Đọc file thành công!");
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi đọc file!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        danhSachMatHang.sort((h1, h2) -> Double.compare(h2.tinhGia(), h1.tinhGia()));
        hienThiLenBang(danhSachMatHang);
        System.out.println("--- DANH SÁCH SAU KHI SẮP XẾP GIẢM DẦN ---");
        for (matHang mh : danhSachMatHang) {
            System.out.println(mh.toString());
        }
        JOptionPane.showMessageDialog(this, "Đã sắp xếp giảm dần theo giá menu!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         //TODO add your handling code here:
        try {
            String input = txtTimKiem.getText().trim();
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Dien vao di");
                return;
            }
            int maCanTim = Integer.parseInt(input);
            ArrayList<matHang> ketQua = new ArrayList<>();
            boolean timThay = false;
            for (matHang mh : danhSachMatHang) {
                if (mh.getMaHang() == maCanTim) {
                    ketQua.add(mh);
                    timThay = true;
                }
            }
            
            if (timThay) {
                hienThiLenBang(ketQua); 
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã: " + maCanTim);
                hienThiLenBang(danhSachMatHang); 
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã hàng phải là số nguyên!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giaoDien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
