
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vuhuy
 */
public class giaoDien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(giaoDien.class.getName());
    private ArrayList<ruong> danhSachRuong;
    /**
     * Creates new form giaoDien
     */
    public giaoDien() {
        initComponents();
        danhSachRuong=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        thongTin1 = new javax.swing.JLabel();
        thongTin2 = new javax.swing.JLabel();
        txtMaRuong = new javax.swing.JTextField();
        txtTenChuHo = new javax.swing.JTextField();
        txtLoaiCayTrong = new javax.swing.JTextField();
        txtThongTin1 = new javax.swing.JTextField();
        txtThongTin2 = new javax.swing.JTextField();
        buttonRuongVuong = new javax.swing.JRadioButton();
        buttonRuongHinhChuNhat = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma ruong");

        jLabel2.setText("Ten chu ho");

        jLabel3.setText("Loai cay trong");

        thongTin1.setText("Thong tin 1");

        thongTin2.setText("Thong tin 2");

        buttonGroup1.add(buttonRuongVuong);
        buttonRuongVuong.setText("Ruong vuong");
        buttonRuongVuong.addActionListener(this::buttonRuongVuongActionPerformed);

        buttonGroup1.add(buttonRuongHinhChuNhat);
        buttonRuongHinhChuNhat.setText("Ruong chu nhat");
        buttonRuongHinhChuNhat.addActionListener(this::buttonRuongHinhChuNhatActionPerformed);

        jButton1.setText("Them ruong vuong");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Them ruong hcn");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Hien thi");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma ruong", "Ten chu ho", "Loai cay trong", "Dien tich"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton4.setText("Luu file");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Vuong/Hcn");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Trong nhieu nhat");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Dien tich > max");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thongTin1)
                                .addGap(18, 18, 18)
                                .addComponent(txtThongTin1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thongTin2)
                                .addGap(18, 18, 18)
                                .addComponent(txtThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLoaiCayTrong)
                                    .addComponent(txtTenChuHo)
                                    .addComponent(txtMaRuong))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonRuongVuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRuongHinhChuNhat))
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaRuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRuongVuong)
                            .addComponent(buttonRuongHinhChuNhat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLoaiCayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thongTin1)
                            .addComponent(txtThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thongTin2)
                            .addComponent(txtThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRuongVuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRuongVuongActionPerformed
        // TODO add your handling code here:
        if(buttonRuongVuong.isSelected()){
            thongTin1.setText("Do dai canh");
            txtThongTin2.setEditable(false);
            txtThongTin2.setText("Khong duoc nhap");
        }
    }//GEN-LAST:event_buttonRuongVuongActionPerformed

    private void buttonRuongHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRuongHinhChuNhatActionPerformed
        // TODO add your handling code here:
        if(buttonRuongHinhChuNhat.isSelected()){
            txtThongTin2.setEditable(true);
            txtThongTin2.setText("");
            thongTin1.setText("Chieu dai");
            thongTin2.setText("Chieu rong");
        }
    }//GEN-LAST:event_buttonRuongHinhChuNhatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ruongVuong rv=new ruongVuong();
        rv.setMaRuong(Integer.parseInt(txtMaRuong.getText()));
        rv.setTenChuHo(txtTenChuHo.getText());
        rv.setLoaiCayTrong(txtLoaiCayTrong.getText());
        rv.setDoDaiCanh(Double.parseDouble(txtThongTin1.getText()));
        if(buttonRuongVuong.isSelected()){
            rv.tinhDienTich();
            danhSachRuong.add(rv);
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ruongHinhChuNhat rhcn=new ruongHinhChuNhat();
        rhcn.setMaRuong(Integer.parseInt(txtMaRuong.getText()));
        rhcn.setTenChuHo(txtTenChuHo.getText());
        rhcn.setLoaiCayTrong(txtLoaiCayTrong.getText());
        rhcn.setChieuDai(Double.parseDouble(txtThongTin1.getText()));
        rhcn.setChieuRong(Double.parseDouble(txtThongTin2.getText()));
        if(buttonRuongHinhChuNhat.isSelected()){
            rhcn.tinhDienTich();
            danhSachRuong.add(rhcn);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hienThiLenBang(danhSachRuong);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter fw = new FileWriter("ruong.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            for (ruong r : danhSachRuong) {
                String line = "";
                line = r.toString();
                bw.write(line);
                bw.newLine(); 
            }
            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(this, "Lưu file thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lưu file!");
            e.printStackTrace();
        }     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int countVuong = 0;
        int countHCN = 0;
        for (ruong r : danhSachRuong){ 
            if(r instanceof ruongVuong){
                countVuong++;
            } else if(r instanceof ruongHinhChuNhat){
                countHCN++;
            }
        }
        String thongBao="So luong ruong hinh vuong: " + countVuong + "\n" +
                        "So luong ruong hinh chu nhat: " + countHCN;
        javax.swing.JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    String cayNhieuNhat = "";
    int kyLucSoLuong = 0;
    for (ruong r1 : danhSachRuong) {      
        int dem = 0;
        String tenCayCuaA = r1.getLoaiCayTrong();
        for (ruong r2 : danhSachRuong) {
            if (r2.getLoaiCayTrong().equals(tenCayCuaA)) {
                dem++; 
            }
        }
        if (dem > kyLucSoLuong) {
            kyLucSoLuong = dem;
            cayNhieuNhat = tenCayCuaA;
        }
    }
    javax.swing.JOptionPane.showMessageDialog(this, "Cây trồng nhiều nhất: " + cayNhieuNhat + "\n" + "Số lượng: " + kyLucSoLuong + " ruộng");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int countVuotQuaMax=0;
        for(ruong r:danhSachRuong){
            if(r.tinhDienTich()>r.getDienTichMax()){
                countVuotQuaMax++;
            }
        }
        String thongBao="So luong ruong vuot qua 100m: " + countVuotQuaMax;
        javax.swing.JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_jButton7ActionPerformed
    public void hienThiLenBang(ArrayList<ruong> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (ruong r : list) {
            model.addRow(new Object[]{
                r.getMaRuong(),
                r.getTenChuHo(),
                r.getLoaiCayTrong(),
                String.format("%.2f", r.tinhDienTich()) 
            });
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new giaoDien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonRuongHinhChuNhat;
    private javax.swing.JRadioButton buttonRuongVuong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JLabel thongTin1;
    private javax.swing.JLabel thongTin2;
    private javax.swing.JTextField txtLoaiCayTrong;
    private javax.swing.JTextField txtMaRuong;
    private javax.swing.JTextField txtTenChuHo;
    private javax.swing.JTextField txtThongTin1;
    private javax.swing.JTextField txtThongTin2;
    // End of variables declaration//GEN-END:variables
}
